// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7HlsMtz5FHdUJaKAa7UGiEf9Y48Qv80',
    appId: '1:351105783482:web:f992ab9f7713e328441483',
    messagingSenderId: '351105783482',
    projectId: 'service-app-cb14a',
    authDomain: 'service-app-cb14a.firebaseapp.com',
    storageBucket: 'service-app-cb14a.firebasestorage.app',
    measurementId: 'G-YB23ZHBG3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WNvpKQ98jJCIp5v6p2cHCoEIUilop-8',
    appId: '1:351105783482:android:30490b9661a91182441483',
    messagingSenderId: '351105783482',
    projectId: 'service-app-cb14a',
    storageBucket: 'service-app-cb14a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4D5TXiHghhzewUu6DbsVRwqWET477gok',
    appId: '1:351105783482:ios:80e5e895070d1677441483',
    messagingSenderId: '351105783482',
    projectId: 'service-app-cb14a',
    storageBucket: 'service-app-cb14a.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4D5TXiHghhzewUu6DbsVRwqWET477gok',
    appId: '1:351105783482:ios:80e5e895070d1677441483',
    messagingSenderId: '351105783482',
    projectId: 'service-app-cb14a',
    storageBucket: 'service-app-cb14a.firebasestorage.app',
    iosBundleId: 'com.example.serviceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY7HlsMtz5FHdUJaKAa7UGiEf9Y48Qv80',
    appId: '1:351105783482:web:ed1928e640213a0b441483',
    messagingSenderId: '351105783482',
    projectId: 'service-app-cb14a',
    authDomain: 'service-app-cb14a.firebaseapp.com',
    storageBucket: 'service-app-cb14a.firebasestorage.app',
    measurementId: 'G-G5ZFE4EJLG',
  );
}
